image: docker:latest

services:
  - docker:dind
stages:
    - build
    - test
    - deploy

## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
##  DEV - BUILD - START
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
build_dev:
  tags:
    - ixcheck-build
  only:
      - developer
  except:
      - master
      - demo
      - qat
      - feature
  stage: build
  script:
    - docker build -t dev-cust-app -f Dockerfile.dev .
    - docker rmi -f $(docker images -q --filter label=stage=dev-cust-app.intermediate) || true
    - docker tag dev-cust-app hub.ixcheck.io/frontend/dev-cust-ixcheck-app
    - docker login -u $HUB_IXCHECK_IO_USER -p $HUB_IXCHECK_IO_PASS hub.ixcheck.io
    - docker push hub.ixcheck.io/frontend/dev-cust-ixcheck-app
  environment:
    name: developer
 
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
##  DEV- BUILD - END
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #    

## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
##  QAT - BUILD - START
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
build_qat:
  tags:
    - qat-ixcheck-build
  only:
      - qat
  except:
      - master
      - demo
      - developer
      - feature
  stage: build
  script:
    - docker build -t qat-cust-app -f Dockerfile.qat .
    - docker rmi -f $(docker images -q --filter label=stage=qat-cust-app.intermediate) || true
    - docker tag qat-cust-app hub.ixcheck.io/frontend/qat-cust-ixcheck-app
    - docker login -u $HUB_IXCHECK_IO_USER -p $HUB_IXCHECK_IO_PASS hub.ixcheck.io
    - docker push hub.ixcheck.io/frontend/qat-cust-ixcheck-app
  environment:
    name: qat
 
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
##  QAT- BUILD - END
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
##  DEMO - BUILD - START
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
build_demo:
  tags:
    - demo-ixcheck-build
  only:
      - demo
  except:
      - master
      - qat
      - developer
      - feature      
  stage: build
  script:
    - docker build -t demo-cust-app -f Dockerfile.demo .
    - docker rmi -f $(docker images -q --filter label=stage=demo-cust-app.intermediate) || true
    - docker tag demo-cust-app hub.ixcheck.io/frontend/demo-cust-ixcheck-app
    - docker login -u $HUB_IXCHECK_IO_USER -p $HUB_IXCHECK_IO_PASS hub.ixcheck.io
    - docker push hub.ixcheck.io/frontend/demo-cust-ixcheck-app
  environment:
    name: demo
 
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
##  DEMO- BUILD - END
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
##  PROD - BUILD - START
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
build_production:
  tags:
    - prod-ixcheck-build
  only:
      - tags
  except:
      - demo
      - qat
      - developer
      - feature      
  stage: build
  script:
    - docker build -t prod-cust-app -f Dockerfile.prod .
    - docker rmi -f $(docker images -q --filter label=stage=prod-cust-app.intermediate) || true
    - docker tag prod-cust-app hub.ixcheck.io/frontend/prod-cust-ixcheck-app
    - docker login -u $HUB_IXCHECK_IO_USER -p $HUB_IXCHECK_IO_PASS hub.ixcheck.io
    - docker push hub.ixcheck.io/frontend/prod-cust-ixcheck-app
  environment:
    name: master
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
##  BUILD - END
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
##  DEV DEPLOY - START
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
deploy_dev:dev-ixcheck-saas:
  tags:
    - dev-ixcheck-saas
  only:
      - developer
  except:
      - master
      - demo
      - qat
      - feature
  stage: test
  script:
    - docker login -u $HUB_IXCHECK_IO_USER -p $HUB_IXCHECK_IO_PASS hub.ixcheck.io
    - docker stop dev.cust.ixcheck.io || true
    - docker rm dev.cust.ixcheck.io || true
    - docker rmi dev-cust-app | grep dev-cust-app || true
    - docker rmi hub.ixcheck.io/frontend/dev-cust-ixcheck-app | grep dev-cust-app || true
    - docker pull hub.ixcheck.io/frontend/dev-cust-ixcheck-app
    - docker run --name dev.cust.ixcheck.io -d -p 20002:80 --restart=always hub.ixcheck.io/frontend/dev-cust-ixcheck-app
  environment:
    name: developer
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
##  DEV DEPLOY - END
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
##  QAT DEPLOY - START
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
deploy_qat:qat-ixcheck-saas:
  tags:
    - qat-ixcheck-saas
  only:
      - qat
  except:
      - master
      - demo
      - developer
      - feature      
  stage: test
  script:
    - docker login -u $HUB_IXCHECK_IO_USER -p $HUB_IXCHECK_IO_PASS hub.ixcheck.io
    - docker stop qat.cust.ixcheck.io || true
    - docker rm qat.cust.ixcheck.io || true
    - docker rmi qat-cust-ixcheck-app | grep qat-cust-ixcheck-app || true
    - docker rmi hub.ixcheck.io/frontend/qat-cust-ixcheck-app | grep qat-cust-ixcheck-app || true
    - docker pull hub.ixcheck.io/frontend/qat-cust-ixcheck-app
    - docker run --name qat.cust.ixcheck.io -d -p 20002:80 --restart=always hub.ixcheck.io/frontend/qat-cust-ixcheck-app
  environment:
    name: qat
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
##  QAT DEPLOY - END
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
##  DEMO DEPLOY - START
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
deploy_demo:demo-ixcheck-deploy:
  tags:
    - demo-ixcheck-saas
  only:
      - demo
  except:
      - master
      - qat
      - developer
      - feature
  stage: test
  script:
    - docker login -u $HUB_IXCHECK_IO_USER -p $HUB_IXCHECK_IO_PASS hub.ixcheck.io
    - docker stop demo.cust.ixcheck.io || true
    - docker rm demo.cust.ixcheck.io || true
    - docker rmi demo-cust-ixcheck-app | grep demo-cust-ixcheck-app || true
    - docker rmi hub.ixcheck.io/frontend/demo-cust-ixcheck-app | grep demo-cust-ixcheck-app || true
    - docker pull hub.ixcheck.io/frontend/demo-cust-ixcheck-app
    # - docker run --name demo.cust.ixcheck.io -d -p 20002:80 --restart=always hub.ixcheck.io/frontend/demo-cust-ixcheck-app
    - docker run --name demo.cust.ixcheck.io -d -p 20002:80 --restart=always -v /opt/configfiles/demo.images/:/usr/share/nginx/html/assets/images/demo.images/ hub.ixcheck.io/frontend/demo-cust-ixcheck-app
  environment:
    name: demo
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
##  DEMO DEPLOY - END
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
##  PROD DEPLOY - START
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
deploy_production:prod-ixcheck-deploy:
  tags:
    - prod-ixcheck-deploy
  only:
      - tags
  except:
      - demo
      - qat
      - developer
      - feature      
  stage: deploy
  script:
    - docker login -u $HUB_IXCHECK_IO_USER -p $HUB_IXCHECK_IO_PASS hub.ixcheck.io
    - docker stop prod.cust.ixcheck.io || true
    - docker rm prod.cust.ixcheck.io || true
    - docker rmi prod-cust-ixcheck-app | grep prod-cust-ixcheck-app || true
    - docker rmi hub.ixcheck.io/frontend/prod-cust-ixcheck-app | grep prod-cust-ixcheck-app || true
    - docker pull hub.ixcheck.io/frontend/prod-cust-ixcheck-app
    - docker run --name prod.cust.ixcheck.io -d -p 20002:80 --restart=always hub.ixcheck.io/frontend/prod-cust-ixcheck-app
  environment:
    name: master
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
##  PROD DEPLOY - END
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
