export enum HandelError {
  ShowAndReturn = 1,
  ShowAndKill = 2,
  HideAndReturn = 3,
  HideAndKill = 4,
}
export enum FuncStatus {
  True = 1,
  False = 2,
  Error = 3,
}
export enum Main {
  getRegistrationList = "getRegistrationList",
  getExamList = "getExamList",
  getTotalExam = "getTotalExam",
  getQuestionPaperDetails = "getQuestionPaperDetails",
  getAuthoringStatusDetail = "getAuthoringStatusDetail",
  getTotalRegistrationDetail = "getTotalRegistrationDetail",
  getRegistrationStatusDetail = "getRegistrationStatusDetail",
  getTotalCentersDetail = "getTotalCentersDetail",
  getAdmitCardDetail = "getAdmitCardDetail",
  getExamStatusDetail = "getExamStatusDetail",
  getPostExamDetail = "getPostExamDetail",
  getRegistrationPerHour = "getRegistrationPerHour"
}
export enum Exam {
  getExamList = "getExamList",
  getExamDetail = "getExamDetail",
  getExamTypeList = "getExamTypeList",
  getLanguageList = "getLanguageList",
  getSubjectList = "getSubjectList",
  getUomsList = "getUomsList",
  getExamByExamId = "getExamByExamId",
  getExamById = "getExamById",
  getGradeList = "getGradeList",
  getPlanStatusList = "getPlanStatusList",
  saveExam = "saveExam",
  updateExam = "updateExam",
  refreshExamList = "refreshExamList",
  getExamDetailsByExamId = "getExamDetailsByExamId",
  getOrderList="getOrderList",
  saveOrder="saveOrder",
  getQuestionOptionSequenceList ="getQuestionOptionSequenceList",
  getQuestionRandomizationOptionList = "getQuestionRandomizationOptionList",
  getQuestionViewOptionList = "getQuestionViewOptionList",
  //// Section
  getSectionList = "getSectionList",
  getDifficultyLevelList = "getDifficultyLevelList",
  getUserSelectedSubjectList = "getUserSelectedSubjectList",
  addNewSection = "addNewSection",
  saveSection = "saveSection",
  getSaveSection = "getSaveSection",
  deleteSection = "deleteSection",
  //Question
  getQuestionTypeList = "getQuestionTypeList",
  getQuestionList = "getQuestionList",
  saveQuestion = "saveQuestion",
  finalizeExam = "finalizeExam",
  deleteQuestion = "deleteQuestion",

  //mock test
  getMockTestExamList = "getMockTestExamList",
  getMockTestQuestionsByExamId = "getMockTestQuestionsByExamId",
  getMockTestQuestionsById = "getMockTestQuestionsById",
  getMockTestQuestionsDetailsById = "getMockTestQuestionsDetailsById",
  addMockQuestionsDetails = "addMockQuestionsDetails",
  updateMockQuestionsDetails = "updateMockQuestionsDetails",
  getMockQuestionsStatusList = "getMockQuestionsStatusList",
  publishMockExam = "publishMockExam",

  //secondary
  getMockTestSecondaryQuestionsDetailsById = "getMockTestSecondaryQuestionsDetailsById",

  // candidates
  getRegisteredCandidatesist = 'getRegisteredCandidatesist',

  //Multi Exam
  getRegistrationList = "getRegistrationList",

  getMockTestQuestionsListByExamId = "getMockTestQuestionsListByExamId",
  getMockTestSubjectList = "getMockTestSubjectList",
  getMockTestLanguageList = "getMockTestLanguageList",
  getMockTestDifficultyLevelList = "getMockTestDifficultyLevelList",
  getMockTestQuestionTypeList = "getMockTestQuestionTypeList"
}

export enum PaymentGateway {
  getPaymentTypeList = "getPaymentTypeList",
  getPaymentDeatils = "getPaymentDeatils",
  addPaymentGatewayInfo = "addPaymentGatewayInfo",
  getPaymentMappingList = "getPaymentMappingList",
  paytmPaymentGateway = "paytmPaymentGateway",
  getPaymentPaytmResponse = "getPaymentPaytmResponse",
  getPaymentPaymentInfo = "getPaymentPaymentInfo",
  getPaymentsList = "getPaymentsList"
}

export enum Author {
  getAssignmentList = "getAssignmentList",
  getAssignmentDetail = "getAssignmentDetail",
  getAssignmentQuestionDetail = "getAssignmentQuestionDetail",
  saveAssignQuestion = "saveAssignQuestion",
  getAssignmentShiftDetail = "getAssignmentShiftDetail",

  getExamDetail = "getExamDetail",
  getExamTypeList = "getExamTypeList",
  getLanguageList = "getLanguageList",
  getSubjectList = "getSubjectList",
  getUomsList = "getUomsList",
  getExamByExamId = "getExamByExamId",
  getExamById = "getExamById",
  getGradeList = "getGradeList",
  getPlanStatusList = "getPlanStatusList",
  saveExam = "saveExam",
  updateExam = "updateExam",

  //// Section
  getSectionList = "getSectionList",
  getDifficultyLevelList = "getDifficultyLevelList",
  getUserSelectedSubjectList = "getUserSelectedSubjectList",
  addNewSection = "addNewSection",
  saveSection = "saveSection",
  getSaveSection = "getSaveSection",
  deleteSection = "deleteSection",
  //Question
  getQuestionTypeList = "getQuestionTypeList",
  getQuestionList = "getQuestionList",
  saveQuestion = "saveQuestion",
  finalizeExam = "finalizeExam",
  deleteQuestion = "deleteQuestion",
  getAuthoringQuestionList = "getAuthoringQuestionList",
  getAuthoringQuestionListByExamId = "getAuthoringQuestionListByExamId",
  getQuestionAssignmentsListById = "getQuestionAssignmentsListById",
  getQuestionDetails = "getQuestionDetails",
  addQuestionDetails = "addQuestionDetails",
  updateQuestionDetails = "updateQuestionDetails",
  getQuestionAssignments = "getQuestionAssignments",
  updateQuestionReviewStatus = "updateQuestionReviewStatus",
  updateQuestionApproveStatus = "updateQuestionApproveStatus",
  getReviewPlanStatusList = "getReviewPlanStatusList",
  getApprovePlanStatusList = "getApprovePlanStatusList",
  getPrimaryQuestionDetails = "getPrimaryQuestionDetails",
  getQuestionAuditTrail = "getQuestionAuditTrail",
  getApprovalAuthorityExamList = "getApprovalAuthorityExamList",
  getApprovalAuthorityExamDetails = "getApprovalAuthorityExamDetails",
  getImporteedAuthors = "getImporteedAuthors",
  updatePrincipalApprover = "updatePrincipalApprover"
}

export enum QuestionRequirement {
  getQuestionRequirementsByExamId = "getQuestionRequirementsByExamId",
  getQuestionRequirementsList = "getQuestionRequirementsList",
  saveQuestionRequirements = "saveQuestionRequirements",
  getExamTypeList = "getExamTypeList",
  getLanguageList = "getLanguageList",
  getSubjectList = "getSubjectList",
  getPlanStatusList = "getPlanStatusList",
}

export enum Centre {
  getDaysList = "getDaysList",
  getRegistrationSummary = "getRegistrationSummary",
  getShiftsDetailsList = "getShiftsDetailsList",
  getAssignPrefA = "getAssignPrefA",
  getAssignPrefCentreList = "getAssignPrefCentreList",
  getAddedCentreList = "getAddedCentreList",
  updateShiftExamMain = "updateShiftExamMain",
  updateSelectedCentreList = "updateSelectedCentreList",
  getOptionList = "getOptionList",
  updateAddCentreData = "updateAddCentreData",
  getCentrePlanStatus = "getCentrePlanStatus",
  getAssignPrefB = "getAssignPrefB",
  updateSelectedCentreListB = "updateSelectedCentreListB",
  getAssignPrefCentreListB = "getAssignPrefCentreListB",
  updateAddCentreDataB = "updateAddCentreDataB",
  getAddedCentreListB = "getAddedCentreListB",
  copySnapshot="copySnapshot",
  getSnapshotOptionList="getSnapshotOptionList",
  getAssignPrefC = "getAssignPrefC",
  updateSelectedCentreListC = "updateSelectedCentreListC",
  getAssignPrefCentreListC = "getAssignPrefCentreListC",
  updateAddCentreDataC = "updateAddCentreDataC",
  getAddedCentreListC = "getAddedCentreListC",

  getAssignPrefFinal = "getAssignPrefFinal",
  assignpreftotal = "assignpreftotal",
  getCentreTypeList = "getCentreTypeList",
  deleteCentreTypeById = "deleteCentreTypeById",
  saveCentreType = "saveCentreType",
  getCentreTypeById = "getCentreTypeById",
  updateCentreType = "updateCentreType",
  getExamList = "getExamList",
  getExamDetail = "getExamDetail",
  updateExamShift = "updateExamShift",
  getExamShiftMainById = "getExamShiftMainById",
  getNumberOfShifts = "getNumberOfShifts",
  getStates = "getStates",
  getCitiesById = "getCitiesById",
  updateExamShiftMain = "updateExamShiftMain",
  getExamCityStudent = "getExamCityStudent",
  updateExamShiftMainStudent = "updateExamShiftMainStudent",
  getExamCentreList = "getExamCentreList",
  addExamCentre = "addExamCentre",
  getCenterRegistrationsList = "getCenterRegistrationsList",
  getExamTypeList = "getExamTypeList",
  importRegistration = "importRegistration",
  getAlgoList = "getAlgoList",
  deleteAssignPrefCenter = "deleteAssignPrefCenter",
  getReportByShift = "getReportByShift",
  getReportByCenter = "getReportByCenter",
  getCentreListForEdit = "getCentreListForEdit",
  bulkEditCentreList = "bulkEditCentreList",
  getStatesList = "getStatesList",
  getCitiesList = "getCitiesList",
  getSnapshotList = "getSnapshotList",
  getSnapshotInfo = "getSnapshotInfo",
  getExistedSnapshotList = "getExistedSnapshotList",
  updateShiftSnapshot = "updateShiftSnapshot",
  getCentreImportedCode = "getCentreImportedCode",
  getCentreExamCode = "getCentreExamCode",
  getCentreListByImportCode = "getCentreListByImportCode",
  addCentres = "addCentres",
  getAddedCentreListBySnapShotId = "getAddedCentreListBySnapShotId",
  editCentres = "editCentres",
  getShiftNumbers = "getShiftNumbers",
  getAllocationAlgo = "getAllocationAlgo",
  getSnapshotCentreImportedDetails = "getSnapshotCentreImportedDetails",
  allocateAlgoPreference = "allocateAlgoPreference",
  getRandomAlgoList = "getRandomAlgoList",
  getRegistrationData = "getRegistrationData",
  apllyRandomAlgo = "apllyRandomAlgo",
  getRegistrationSummaryByRegGuid = "getRegistrationSummaryByRegGuid",
  getRandomAlgo = "getRandomAlgo",
  finalizeCentrePlanning = "finalizeCentrePlanning"
}
export enum Template {
  getTemplateList = "getTemplateList",
  addTemplate = "addTemplate",
  editTemplate = "editTemplate",
  viewTemplate = "viewTemplate",
  addFromValue = "addFromValue",
}
export enum Candidate {
  getStudentList = "getStudentList",
}

export enum ImportedCentres {
  getImportedCentresList = "getImportedCentresList",
  getImportedCentresById = "getImportedCentresById",
  deleteImportedCentresById = "deleteImportedCentresById",
  getCentresMappingList = "getCentresMappingList",
  getCentresMappingById = "getCentresMappingById",
  saveCentresMapping = "saveCentresMapping",
  getExamTypeList = "getExamTypeList",
  getStatesList = "getStatesList",
  getCitiesList = "getCitiesList",
  getCentresList = "getCentresList",
  getNewCentresList = "getNewCentresList",
  getImportJson = "getImportJson",
  saveImportMeta = "saveImportMeta",
  saveMoreImportMeta = "saveMoreImportMeta",
  getImportedCentresListById = "getImportedCentresListById",
  getImportedNumber = "getImportedNumber",
  getPlanStatus = "getPlanStatus",
  getCentresMappingRefresgList = "getCentresMappingRefresgList",
  getMappedCentresList = "getMappedCentresList",
  getStates = "getStates",
  getCentreTypeList = "getCentreTypeList",
  updateImportedCentres = "updateImportedCentres",
  getImportedCentresListDetails = "getImportedCentresListDetails",
  centresUnMap = "centresUnMap",
  getRegistrationTypeList = "getRegistrationTypeList",

  // getcitysList = "getcitysList"
}
export enum Registration {
  getLayoutList = "getLayoutList",
  getLayoutDropdownList = "getLayoutDropdownList",
  getStudentList = "getStudentList",
  getLayoutMappingList = "getLayoutMappingList",
  getExamMappingList = "getExamMappingList",
  addLayout = "addLayout",
  editLayout = "editLayout",
  viewLayout = "viewLayout",
  addFromValue = "addFromValue",
  getExamTypeList = "getExamTypeList",
  getExamDetails = "getExamDetails",
  deleteLayout = "deleteLayout",
  mapRegistrationLayout = "mapRegistrationLayout",
  getExamList = "getExamList",
  sampleDataView = "sampleDataView",
  getLayoutDetailByExamGuid = "getLayoutDetailByExamGuid",
  addFormValueByExamGuid = "addFormValueByExamGuid",
  getCandidateDetailsByGuid = "getCandidateDetailsByGuid",
  getLayoutTypeList = "getLayoutTypeList",
  getLayoutTypeListByExamId = "getLayoutTypeListByExamId",
  getPublishRegistrationList = "getPublishRegistrationList",
  publishRegistration = "publishRegistration",
  getPlanStatusList = "getPlanStatusList",
  getRegistrationTypeList = "getRegistrationTypeList",
  getRegistrationDetailsByGuid = "getRegistrationDetailsByGuid",
  getLayoutTypeListByRegistrationId = "getLayoutTypeListByRegistrationId",
  getPaymentGatewayTypeList = "getPaymentGatewayTypeList",
  getPaymentGatewayEnvironmentList = "getPaymentGatewayEnvironmentList",
  getPaymentGatewayDetails = "getPaymentGatewayDetails",
  updateRegistrationPaymentGatewayDetail = "updateRegistrationPaymentGatewayDetail",
  updatePaytmConfigDetail = "updatePaytmConfigDetail",
  updatePayumoneyConfigDetail = "updatePayumoneyConfigDetail",
  updateRazorPayConfigDetail = "updateRazorPayConfigDetail"
}

export enum RegistrationsSetup {
  verifiedMail = "verifiedMail",
  getRegistrationsSetupByExamId = "getRegistrationsSetupByExamId",
  getRegistrationsSetupList = "getRegistrationsSetupList",
  getRegistrationsSetupDetailsByExamId = "getRegistrationsSetupDetailsByExamId",
  saveRegistrationsSetup = "saveRegistrationsSetup",
  addRegistrationsSetupDetails = "addRegistrationsSetupDetails",
  updateRegistrationsSetupDetails = "updateRegistrationsSetupDetails",
  getExamTypeList = "getExamTypeList",
  getFeeSetupMasterList = "getFeeSetupMasterList",
  getLanguageList = "getLanguageList",
  getSubjectList = "getSubjectList",
  getPlanStatusList = "getPlanStatusList",
  getApplicableFeesSetupList = "getApplicableFeesSetupList",
  getFeesSetupList = "getFeesSetupList",
  updateFeesSetupList = "updateFeesSetupList",
  deleteApplicableFeeSetup = "deleteApplicableFeeSetup",
  updateApplicableFeesSetup = "updateApplicableFeesSetup",
  getRegistrationsEmailServerDetailsByExamId = "getRegistrationsEmailServerDetailsByExamId",
  addRegistrationsEmailServerDetails = "addRegistrationsEmailServerDetails",
  updateRegistrationsEmailServerDetails = "updateRegistrationsEmailServerDetails",
}
export enum Registrations {
  getExamList = "getExamList",
  addRegBasicSetupDetails = "addRegBasicSetupDetails",
  getRegistrationList = "getRegistrationList",
  getExamTypeList = "getExamTypeList",
  getRegPlanStatusList = "getRegPlanStatusList",
  getExamListByRegistrationGuid = "getExamListByRegistrationGuid",
  getRegBasicSetupDetailsByRegGuid = "getRegBasicSetupDetailsByRegGuid",
  updateRegBasicSetupDetails = "updateRegBasicSetupDetails",
  getRegTypeList = "getRegTypeList",
  addRegType = "addRegType",
  getRegTypeByGuid = "getRegTypeByGuid",
  updateRegType = "updateRegType",
  addRegTypeMapping = "addRegTypeMapping",
  getRegTypeMappingListByGuid = "getRegTypeMappingListByGuid",
  updateRegTypeMapping = "updateRegTypeMapping",
  getFeeTypeList = "getFeeTypeList",
  getApplicableFeeList = "getApplicableFeeList",
  addFeeApplicableDetails = "addFeeApplicableDetails",
  updateFeeApplicableDetails = "updateFeeApplicableDetails",
  finlizeRegSetupDetails = "finlizeRegSetupDetails",
  getRegSetupFeeByRegGuid = "getRegSetupFeeByRegGuid",
  getRegTypeByRegGuid = "getRegTypeByRegGuid",
  publishRegSetupDetails = "publishRegSetupDetails",
  getStateList = "getStateList",
  getCityList = "getCityList",
  addExamCity = "addExamCity",
  getExamCityListByRegGuid = "getExamCityListByRegGuid",
  addPaymentGateway = "addPaymentGateway",
  getPaymentGatewayList = "getPaymentGatewayList",
  changeRegistrationPaymentGatewayStatus = "changeRegistrationPaymentGatewayStatus"
}
export enum ImportAuthors {
  getSubjectsList = "getSubjectsList",
  getLanguagesList = "getLanguagesList",
  getAuthorsList = "getAuthorsList",
  getImportJson = "getImportJson",
  saveImportMeta = "saveImportMeta",
  getImporteedAuthors = "getImporteedAuthors",
  deleteImporteedAuthors = "deleteImporteedAuthors",
  getImporteedAuthorsById = "getImporteedAuthorsById",
  getSubjects = "getSubjects",
  getLanguages = "getLanguages",
}

export enum AdmitCard {
  getAdmitCardSetupList = "getAdmitCardSetupList",
  getExamTypeList = "getExamTypeList",
  getRegTypeList = "getRegTypeList",
  getLayoutTypeList = "getLayoutTypeList",
  getLayoutList = "getLayoutList",
  viewLayoutPreview = "viewLayoutPreview",
  updateLayoutPreview = "updateLayoutPreview",
  getLayoutMappingList = "getLayoutMappingList",
  getExamDetails = "getExamDetails",
  mapAdmitCardLayout = "mapAdmitCardLayout",
  getAdmitCardLayoutMappingRefreshList = "getCentresMappingRefresgList",
  getPlanStatusList = "getPlanStatusList",
  getMappedLayoutView = "getMappedLayoutView",
  getAdmitCardBasicSetupDetailsByExamId = "getAdmitCardBasicSetupDetailsByExamId",
  updateAdmitCardBasicSetupDetails = "updateAdmitCardBasicSetupDetails",
  getAdmitCardDistributionMethod = "getAdmitCardDistributionMethod",
  getAdmitCardDistributionSchedule = "getAdmitCardDistributionSchedule",
  getAdmitCardSmsDetails = "getAdmitCardSmsDetails",
  addAdmitCardSmsDetails = "addAdmitCardSmsDetails",
  getAdmitCardEmailDetails = "getAdmitCardEmailDetails",
  addAdmitCardEmailDetails = "addAdmitCardEmailDetails",
  getTermAndConditions = "getTermAndConditions",
  addTermAndConditions = "addTermAndConditions",
  finalizeAdmitCard = "finalizeAdmitCard",
  GetAdmitCardExamList = "GetAdmitCardExamList",
  GetAdmitCardExamListRefresh = "GetAdmitCardExamListRefresh",
  GetCentresList = "GetCentresList",
  getNetworksList = "getNetworksList",
  getAdmitCardCentresDetails = "getAdmitCardCentresDetails",
  getpocList = "getpocList",
  getNetworkDetailsList = "getNetworkDetailsList",
  getNetworkForCentreDetails = "getNetworkForCentreDetails",
  getStatesList = "getStatesList",
  getCentreTypeList = "getCentreTypeList",
  getCityList = "getCityList",
  getShiftDetailsList = "getShiftDetailsList",
  getAdmitCardListByCityId = "getAdmitCardListByCityId",
  getAdmitCardList = "getAdmitCardList",
  getStates = "getStates",
  getCities = "getCities",
  getAdmitCardPreviewDetails = "getAdmitCardPreviewDetails",
  generateAdmitCards = "generateAdmitCards",
  getEmailPreviewDetail = "getEmailPreviewDetail",
  getQrCodeDetails = "getQrCodeDetails",
  addQrBarCodeDetails = "addQrBarCodeDetails",
  getQrBarCodeById = "getQrBarCodeById",
  createPackage = "createPackage",
  publishAdmitCards = "publishAdmitCards",
  getAdmitCardSetupRegList = "getAdmitCardSetupRegList",
  generateRegistration = "generateRegistration",
  getAdmitCardCentreList="getAdmitCardCentreList"
}

export enum Changepassword {
  changepassword = 'changepassword'
}

export enum Packaging {
  getPackageSetupExamList = "getPackageSetupExamList",
  refreshPackageSetupExamList = "refreshPackageSetupExamList",
  getPackageSetupPlanStatusList = "getPackageSetupPlanStatusList",
  getPackageSetupExamType = "getPackageSetupExamType",
  getPackageExamList = "getPackageExamList",
  getPackagePlanStatusList = "getPackagePlanStatusList",
  getPackageExamType = "getPackageExamType",
  getShiftDetailsList = "getShiftDetailsList",
  createPackage = "createPackage",
  getPackageList = "getPackageList",
}

export enum Registered {
  getExamTypeList = "getExamTypeList",
  getCandidateRegistrationStatus = "getCandidateRegistrationStatus",
  getCandidatesExamList = "getCandidatesExamList",
  getRegisteredCandidatesList = "getRegisteredCandidatesList",
  getPaymentExamList = "getPaymentExamList",
  getPaymentManagementList = "getPaymentManagementList",
  getPaymentDetailByPaymentId = "getPaymentDetailByPaymentId",
  getGenderList = "getGenderList",
  getPhList = "getPhList",
  getCategoryList = "getCategoryList",
  getPaymentStatus = "getPaymentStatus",
  getCandidateDetailsByExamGuid = "getCandidateDetailsByExamGuid"
}

export enum Candidates {
  getCandidateRegistrationStatus = "getCandidateRegistrationStatus",
  getPlanStatus = "getPlanStatus",
  getCandidateRegistrationsList = "getCandidateRegistrationsList",
  getCandidateRegistrationsDetail = "getCandidateRegistrationsDetail",
  getRegistrationsPaymentDetail = "getRegistrationsPaymentDetail",

  getGenderList = "getGenderList",
  getCategoryList = "getCategoryList",
  getPaymentStatus = "getPaymentStatus",
  getRegisteredCandidatesList = "getRegisteredCandidatesList",
  getRegisteredCandidateDetail = "getRegisteredCandidateDetail",
  getCandidateInfo = "getCandidateInfo",
  getActivityLogs = "getActivityLogs",
  getCandidateDetailsByExamGuid = "getCandidateDetailsByExamGuid",
  getEligibilityQualification = "getEligibilityQualification",
  createJob = "createJob",
  finalizeRegistration = "finalizeRegistration",
  updateCandidateStatus = "updateCandidateStatus",
  updateCandidateExam = "updateCandidateExam"
}

export enum Configurations {
  verifiedMail = "verifiedMail",
  getRegistrationsEmailServerDetailsByGuid = "getRegistrationsEmailServerDetailsByGuid",
  addRegistrationsEmailServerDetails = "addRegistrationsEmailServerDetails",
  updateRegistrationsEmailServerDetails = "updateRegistrationsEmailServerDetails",
}


export enum Jobs {
  getJobTypesList = "getJobTypesList",
  deleteJobTypesById = "deleteJobTypesById",
  addJobTypes = "addJobTypes",
  getJobTypesById = "getJobTypesById",
  updateJobTypes = "updateJobTypes",
  addJobs = "addJobs",
  getJobTypeList = "getJobTypeList",
  getJobStatusList = "getJobStatusList",
  getJobList = "getJobList",
  getJobDetailsById = "getJobDetailsById",
  updateJobs = "updateJobs"
}
export enum ProfileEdit {
  getUserDataByUserId = "getUserDataByUserId",
  getUserByOrgIdAndUserId = 'getUserByOrgIdAndUserId',
  getOrgsUserTypeDropList = 'getOrgsUserTypeDropList',
  saveEditedOrgsUser = "saveEditedOrgsUser",
  getDepartmrntList = "getDepartmrntList",
  getDesignationList = "getDesignationList",
  getHighestQualification = "getHighestQualification",
  getSubjectList = "getSubjectList",
  getLanguageList = "getLanguageList",
  getOrgnizationType = "getOrgnizationType",
  getIdentityType = "getIdentityType"
}